class _BotCommands:
    def __init__(self):
        self.StartCommand = 'zstart'
        self.MirrorCommand = 'zmirror'
        self.UnzipMirrorCommand = 'zunzip'
        self.TarMirrorCommand = 'ztar'
        self.CancelMirror = 'zcancel'
        self.CancelAllCommand = 'zcnlall'
        self.ListCommand = 'zlist'
        self.StatusCommand = 'zstatus'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.PingCommand = 'ping'
        self.RestartCommand = 'zrestart'
        self.StatsCommand = 'stat'
        self.HelpCommand = 'hlp'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'zclone'
        self.WatchCommand = 'zwatch'
        self.TarWatchCommand = 'ztarwatch'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'usage'
        self.RepoCommand = 'zzzrepo'

BotCommands = _BotCommands()
